// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: breakeven/break-even.proto

package breakeven

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Estimation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownPayment          float64 `protobuf:"fixed64,1,opt,name=downPayment,proto3" json:"downPayment,omitempty"`
	MortgageInterestRate float64 `protobuf:"fixed64,2,opt,name=mortgageInterestRate,proto3" json:"mortgageInterestRate,omitempty"`
	PropertyTax          float64 `protobuf:"fixed64,3,opt,name=propertyTax,proto3" json:"propertyTax,omitempty"`
	PropertyTransferTax  float64 `protobuf:"fixed64,4,opt,name=propertyTransferTax,proto3" json:"propertyTransferTax,omitempty"`
	Term                 int64   `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *Estimation) Reset() {
	*x = Estimation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breakeven_break_even_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estimation) ProtoMessage() {}

func (x *Estimation) ProtoReflect() protoreflect.Message {
	mi := &file_breakeven_break_even_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estimation.ProtoReflect.Descriptor instead.
func (*Estimation) Descriptor() ([]byte, []int) {
	return file_breakeven_break_even_proto_rawDescGZIP(), []int{0}
}

func (x *Estimation) GetDownPayment() float64 {
	if x != nil {
		return x.DownPayment
	}
	return 0
}

func (x *Estimation) GetMortgageInterestRate() float64 {
	if x != nil {
		return x.MortgageInterestRate
	}
	return 0
}

func (x *Estimation) GetPropertyTax() float64 {
	if x != nil {
		return x.PropertyTax
	}
	return 0
}

func (x *Estimation) GetPropertyTransferTax() float64 {
	if x != nil {
		return x.PropertyTransferTax
	}
	return 0
}

func (x *Estimation) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E                     *Estimation `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
	Rent                  float64     `protobuf:"fixed64,2,opt,name=rent,proto3" json:"rent,omitempty"`
	PriceOfPotentialHouse float64     `protobuf:"fixed64,3,opt,name=priceOfPotentialHouse,proto3" json:"priceOfPotentialHouse,omitempty"`
	LoanTerm              int64       `protobuf:"varint,4,opt,name=loanTerm,proto3" json:"loanTerm,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breakeven_break_even_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_breakeven_break_even_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_breakeven_break_even_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetE() *Estimation {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *Request) GetRent() float64 {
	if x != nil {
		return x.Rent
	}
	return 0
}

func (x *Request) GetPriceOfPotentialHouse() float64 {
	if x != nil {
		return x.PriceOfPotentialHouse
	}
	return 0
}

func (x *Request) GetLoanTerm() int64 {
	if x != nil {
		return x.LoanTerm
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_breakeven_break_even_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_breakeven_break_even_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_breakeven_break_even_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_breakeven_break_even_proto protoreflect.FileDescriptor

var file_breakeven_break_even_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x2f, 0x62, 0x72, 0x65, 0x61,
	0x6b, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a,
	0x0a, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x6f, 0x77, 0x6e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a,
	0x14, 0x6d, 0x6f, 0x72, 0x74, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73,
	0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x6d, 0x6f, 0x72,
	0x74, 0x67, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x61, 0x78,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x54, 0x61, 0x78, 0x12, 0x30, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x13, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x54, 0x61, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x8a, 0x01, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x01, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x72, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x15, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50,
	0x6f, 0x74, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x15, 0x70, 0x72, 0x69, 0x63, 0x65, 0x4f, 0x66, 0x50, 0x6f, 0x74, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f,
	0x61, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x6f,
	0x61, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x3f, 0x0a, 0x10, 0x42, 0x72,
	0x65, 0x61, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b,
	0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x72, 0x65, 0x61, 0x6b,
	0x45, 0x76, 0x65, 0x6e, 0x12, 0x08, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x65, 0x6e, 0x69, 0x62,
	0x6c, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x31, 0x30, 0x31, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x2d, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x2f,
	0x62, 0x72, 0x65, 0x61, 0x6b, 0x65, 0x76, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_breakeven_break_even_proto_rawDescOnce sync.Once
	file_breakeven_break_even_proto_rawDescData = file_breakeven_break_even_proto_rawDesc
)

func file_breakeven_break_even_proto_rawDescGZIP() []byte {
	file_breakeven_break_even_proto_rawDescOnce.Do(func() {
		file_breakeven_break_even_proto_rawDescData = protoimpl.X.CompressGZIP(file_breakeven_break_even_proto_rawDescData)
	})
	return file_breakeven_break_even_proto_rawDescData
}

var file_breakeven_break_even_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_breakeven_break_even_proto_goTypes = []interface{}{
	(*Estimation)(nil), // 0: Estimation
	(*Request)(nil),    // 1: Request
	(*Response)(nil),   // 2: Response
}
var file_breakeven_break_even_proto_depIdxs = []int32{
	0, // 0: Request.e:type_name -> Estimation
	1, // 1: BreakEvenService.CalculateBreakEven:input_type -> Request
	2, // 2: BreakEvenService.CalculateBreakEven:output_type -> Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_breakeven_break_even_proto_init() }
func file_breakeven_break_even_proto_init() {
	if File_breakeven_break_even_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_breakeven_break_even_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estimation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_breakeven_break_even_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_breakeven_break_even_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_breakeven_break_even_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_breakeven_break_even_proto_goTypes,
		DependencyIndexes: file_breakeven_break_even_proto_depIdxs,
		MessageInfos:      file_breakeven_break_even_proto_msgTypes,
	}.Build()
	File_breakeven_break_even_proto = out.File
	file_breakeven_break_even_proto_rawDesc = nil
	file_breakeven_break_even_proto_goTypes = nil
	file_breakeven_break_even_proto_depIdxs = nil
}
