// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package breakeven

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BreakEvenServiceClient is the client API for BreakEvenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BreakEvenServiceClient interface {
	CalculateBreakEven(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type breakEvenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBreakEvenServiceClient(cc grpc.ClientConnInterface) BreakEvenServiceClient {
	return &breakEvenServiceClient{cc}
}

func (c *breakEvenServiceClient) CalculateBreakEven(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/BreakEvenService/CalculateBreakEven", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreakEvenServiceServer is the server API for BreakEvenService service.
// All implementations must embed UnimplementedBreakEvenServiceServer
// for forward compatibility
type BreakEvenServiceServer interface {
	CalculateBreakEven(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBreakEvenServiceServer()
}

// UnimplementedBreakEvenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBreakEvenServiceServer struct {
}

func (UnimplementedBreakEvenServiceServer) CalculateBreakEven(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateBreakEven not implemented")
}
func (UnimplementedBreakEvenServiceServer) mustEmbedUnimplementedBreakEvenServiceServer() {}

// UnsafeBreakEvenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BreakEvenServiceServer will
// result in compilation errors.
type UnsafeBreakEvenServiceServer interface {
	mustEmbedUnimplementedBreakEvenServiceServer()
}

func RegisterBreakEvenServiceServer(s grpc.ServiceRegistrar, srv BreakEvenServiceServer) {
	s.RegisterService(&BreakEvenService_ServiceDesc, srv)
}

func _BreakEvenService_CalculateBreakEven_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakEvenServiceServer).CalculateBreakEven(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BreakEvenService/CalculateBreakEven",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakEvenServiceServer).CalculateBreakEven(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BreakEvenService_ServiceDesc is the grpc.ServiceDesc for BreakEvenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BreakEvenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BreakEvenService",
	HandlerType: (*BreakEvenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateBreakEven",
			Handler:    _BreakEvenService_CalculateBreakEven_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breakeven/break-even.proto",
}
